# 1. numpy?

In [1]:
import numpy as np

nums = [1, 2, 3]
result = [n * 2 for n in nums]

arr = np.array([1, 2, 3])
result2 = arr * 2

print("python list: ", nums, result)
print("np array: ", arr, result2)

python list:  [1, 2, 3] [2, 4, 6]
np array:  [1 2 3] [2 4 6]


# 2. 배열 생성 문법

In [ ]:
import numpy as np

a = np.array([1, 2, 3], dtype=float)    # dtype 명시
b = np.zeros((2, 3))                    # 2x3 영행렬
c = np.arange(0, 10, 2)                 # [0 2 4 6 8]
d = np.linspace(0, 1, 5)                # 0~1 균등 분할 5개 값

print(a, b, c, d)

[1. 2. 3.] [[0. 0. 0.]
 [0. 0. 0.]] [0 2 4 6 8] [0.   0.25 0.5  0.75 1.  ]


# 3. 배열의 주요 속성

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print('차원: ', arr.ndim)
print('모양:', arr.shape)           # (2, 3) -> 2행 3열
print('전체 개수:', arr.size)       # 6
print('자료형:', arr.dtype)         # int64
print('자료형 크기:', arr.itemsize) # 8 bytes

차원:  2
모양: (2, 3)
전체 개수: 6
자료형: int64
자료형 크기 8


# 4. 형태 변환: reshape, flatten

In [6]:
import numpy as np

arr = np.arange(12)         # 0~11, 1차원 12개
mat = arr.reshape(3, 4)     # 3행 4열로 변환
print(mat)

flat = mat.flatten()        # 다시 1차원으로 펼치기
print(flat)

auto = arr.reshape(2, -1)   # 2행, 열은 자동 계산(=6)
print(auto.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(2, 6)


# 5. 인덱싱과 슬라이싱

In [ ]:
import numpy as np

arr = np.array(
    [[10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]]
)

print(arr[0])
print(arr[1, 2])
print(arr[:, 0])
print(arr[0:2, 1:3])

[10 20 30]
60
[10 40 70]
[[20 30]
 [50 60]]


# 6. 불리언 인덱싱; 조건필터

In [9]:
import numpy as np

temps = np.array([21.2, 22.1, 24.0, 30.5, 25.2])

mask = temps >= 24      # [False False True True True]
warning = temps[mask]   # 조건을 만족하는 값만 추출
print(warning)          # [24. 30.5 25.2]

print(temps[temps >= 24])

temps[temps >= 30] = 30.0 # 30도 이상은 30으로 clip
print(temps)

[24.  30.5 25.2]
[24.  30.5 25.2]
[21.2 22.1 24.  30.  25.2]


# 7. 배열 연산과 브로드캐스팅

In [10]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a + b)
# [11 22 33]
print(a * 2)
# [2 4 6] (스칼라 브로드캐스팅)
mat = np.array([[1,2,3],[4,5,6]])
row = np.array([10,20,30])
print(mat + row) # 각 행에 더함


[11 22 33]
[2 4 6]
[[11 22 33]
 [14 25 36]]


# 8. 집계 함수와 axis;축 연산

In [ ]:
import numpy as np

data = np.array([[20, 60], # [온도, 습도] - 센서1
[22, 55], # - 센서2
[25, 58]]
) # - 센서3

print('전체 평균:', data.mean())
print('열별 평균(axis=0):', data.mean(axis=0))
print('행별 평균(axis=1):', data.mean(axis=1))
print('가장 더운 센서:', np.argmax(data[:, 0]))


전체 평균: 40.0
열별 평균(axis=0): [22.33333333 57.66666667]
행별 평균(axis=1): [40.  38.5 41.5]
가장 더운 센서: 2


# 9. 예제

## 예제1

In [ ]:
import numpy as np

# 5개 센서의 온도값을 배열로 생성
temps = np.array([21.5, 30.2, 26.1, 33.4, 19.8])

print('배열:', temps)
print('차원:', temps.ndim) # 1
print('모양:', temps.shape) # (5,)
print('자료형:', temps.dtype) # float64

배열: [21.5 30.2 26.1 33.4 19.8]
차원: 1
모양: (5,)
자료형: float64


## 예제2

In [ ]:
import numpy as np

# 10개의 값을 5개 시점 x 2개 센서 구조로 재구성
raw = np.arange(10) # [0 1 ... 9]
log = raw.reshape(5, 2) # 5행 2열

print(log)
print('시점 수:', log.shape[0])
print('센서 수:', log.shape[1])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
시점 수: 5
센서 수: 2


## 예제3

In [14]:
import numpy as np
temps = np.array([21.5, 30.2, 26.1, 33.4, 19.8])

# 30도 이상인 값만 추출
alerts = temps[temps >= 30]
print('경고 값:', alerts)

# 몇 개인지 개수 세기
count = (temps >= 30).sum()
print('경고 건수:', count)

경고 값: [30.2 33.4]
경고 건수: 2


## 예제4

In [15]:
import numpy as np
data = np.array([[20, 60],
[22, 55],
[31, 58]])

col_mean = data.mean(axis=0) # [온도평균, 습도평균]
row_max = data.max(axis=1) # 센서별 최댓값

print('열 평균:', col_mean)
print('행 최댓값:', row_max)

열 평균: [24.33333333 57.66666667]
행 최댓값: [60 55 58]


## 예제5

In [ ]:
import numpy as np

celsius = np.array([20.0, 25.0, 30.0, 35.0])
# 섭씨 -> 화씨 변환을 배열 전체에 한 번에 적용
fahrenheit = celsius * 9 / 5 + 32

print('섭씨:', celsius)
print('화씨:', fahrenheit)

섭씨: [20. 25. 30. 35.]
화씨: [68. 77. 86. 95.]


# 11. 확인 문제

In [18]:
# 1) np.arange(1, 13)를 (3, 4) 모양으로 reshape하라.
# 2) 위 배열에서 axis=0 합계와 axis=1 합계를 각각 구하라

import numpy as np

arr = np.arange(1, 13).reshape(3, 4)
print(arr.sum(axis=0)) # 열 합계
print(arr.sum(axis=1)) # 행 합계

[15 18 21 24]
[10 26 42]


In [19]:
# 3) 1차원 배열에서 평균보다 큰 값만 불리언 인덱싱으로 추출하라.
x = np.array([2, 8, 4, 10, 3])
print(x[x > x.mean()])

[ 8 10]


In [20]:
# 4) a=np.array([1,2,3]), b=np.array([[1],[2],[3]])의 a+b 결과 모양을 예측 후 확인하라
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)

(3, 3)


In [21]:
# 5) 섭씨 배열을 화씨로 변환한 뒤 90 이상인 값의 개수를 구하라.
celsius = np.array([28, 30, 34, 20])
fahrenheit = celsius * 9 / 5 + 32

print((fahrenheit >= 90).sum())

1
